export interface Emoji {
  name: string;
  unicode: string;
}

export const EMOJIS: Emoji[] = [
  { name: 'check-mark', unicode: '✅' },
  { name: 'thumbs-up', unicode: '👍' },

  { name: 'nerd', unicode: '🤓' },
  { name: 'rocket', unicode: '🚀' },
  { name: 'folded-hands', unicode: '🙏' },
  { name: 'face-with-tears-of-joy', unicode: '😂' },
  { name: 'rolling-on-the-floor-laughing', unicode: '🤣' },
  { name: 'smiling-face-with-open-mouth-and-cold-sweat', unicode: '😅' },
  { name: 'smiling-face-with-tear', unicode: '🥲' },
  { name: 'loudly-crying-face', unicode: '😭' },
  { name: 'hugging-face', unicode: '🤗' },
  { name: 'face-blowing-a-kiss', unicode: '😘' },
  { name: 'smiling-face-with-hearts', unicode: '🥰' },
  { name: 'two-hearts', unicode: '💕' },
  { name: 'smiling-face-with-heart-eyes', unicode: '😍' },
  { name: 'smiling-face-with-smiling-eyes', unicode: '😊' },
  { name: 'face-savoring-food', unicode: '😋' },
  { name: 'grinning-face-with-smiling-eyes', unicode: '😁' },
  { name: 'smiling-face-with-sunglasses', unicode: '😎' },
  { name: 'star-struck', unicode: '🤩' },
  { name: 'winking-face', unicode: '😉' },
  { name: 'face-with-hand-over-mouth', unicode: '🤭' },
  { name: 'face-with-rolling-eyes', unicode: '🙄' },
  { name: 'face-with-pleading-eyes', unicode: '🥺' },
  { name: 'thinking-face', unicode: '🤔' },
  { name: 'fire', unicode: '🔥' },
  { name: 'clapping-hands', unicode: '👏' },
  { name: 'hands-up', unicode: '🙌' },
  { name: 'flexed-biceps', unicode: '💪' },
  { name: 'zany-face', unicode: '🤪' },
  { name: 'money-mouth-face', unicode: '🤑' },
  { name: 'partying-face', unicode: '🥳' },
  { name: 'party-popper', unicode: '🎉' },
  { name: 'confetti-ball', unicode: '🎊' },
  { name: 'sparkles', unicode: '✨' },
  { name: 'dog-face', unicode: '🐶' },
  { name: 'cat-face', unicode: '🐱' },
  { name: 'rose', unicode: '🌹' },
  { name: 'sunflower', unicode: '🌻' },
  { name: 'butterfly', unicode: '🦋' },
  { name: 'red-heart', unicode: '❤️' },
  { name: 'purple-heart', unicode: '💜' },
  { name: 'blue-heart', unicode: '💙' },
  { name: 'yellow-heart', unicode: '💛' },
  { name: 'broken-heart', unicode: '💔' },
  { name: 'face-with-monocle', unicode: '🧐' },
  { name: 'sleeping-face', unicode: '😴' },
  { name: 'zzz', unicode: '💤' },
  { name: 'pensive-face', unicode: '😔' },
  { name: 'confused-face', unicode: '😕' },
  { name: 'face-with-medical-mask', unicode: '😷' },
  { name: 'face-with-head-bandage', unicode: '🤕' },
  { name: 'exploding-head', unicode: '🤯' },
  { name: 'cold-face', unicode: '🥶' },
  { name: 'nauseated-face', unicode: '🤢' },
  { name: 'face-vomiting', unicode: '🤮' },
  { name: 'hot-face', unicode: '🥵' },
  { name: 'face-with-symbols-on-mouth', unicode: '🤬' },
  { name: 'ghost', unicode: '👻' },
  { name: 'skull', unicode: '💀' },
  { name: 'poop', unicode: '💩' },
  { name: 'eyes', unicode: '👀' },
  { name: 'see-no-evil-monkey', unicode: '🙈' },
  { name: 'hundred-points', unicode: '💯' },
  { name: 'check-box-with-check', unicode: '☑️' },
  { name: 'hourglass', unicode: '⏳' },
  { name: 'light-bulb', unicode: '💡' },
  { name: 'warning', unicode: '⚠️' },
  { name: 'information', unicode: 'ℹ️' },
  { name: 'memo', unicode: '📝' },
];

// [
//   {
//     name: 'check-mark',
//     src: 'assets/img/emoticons/emoji-white-check-mark.svg',
//   },
//   {
//     name: 'hands-up',
//     src: 'assets/img/emoticons/emoji-raising-hands.svg',
//   },

//   {
//     name: 'emoji-nerd',
//     src: 'assets/img/emoticons/emoji-nerd.svg',
//   },
//   {
//     name: 'emoji-rocket',
//     src: 'assets/img/emoticons/emoji-rocket.svg',
//   },
//   {
//     name: 'emoji-thumb',
//     src: 'assets/img/emoticons/emoji-thumb.svg',
//   },
// ];
